### PR TITLE
feat(): XConnector try to leverage generic fabric logic for connectors.

### PR DESCRIPTION
**Pull request by asturur**
## Description

Before patching just the bounding box and consolidate the current logic i want to see if i can remove the extra code from the XConnector class and leverage the fabricJS pathControl utility.

## In Action

image

I m having issue with the color of the first control point, but apart from that seems that replicates the original functionalities and is refactored to be a bit more concise and to leverage fabricJS features

### CODE REVIEW

**Comment by asturur** [comment]
Got an idea of what i have to do:
- the path controls need to take in account of render customization for control points and connecting lines
- the action handler for controls needs to be wrapped for custom behaviour or the 'modifyPath' event needs to have all the information to move the logic there
- the update path strategy there is in XConnector is mostly unneded and we can try to leverage the controls functions to drive the `xConnector.update({ fromPoint, toPoint, ... })` functionality

**Comment by usamshen** [comment]
@asturur can we merge this pr, let me test from boardx app?

**Comment by asturur** [comment]
No i refactored the code twice this weekend and couldn't land on something i appreciated.

**Comment by usamshen** [comment]
i started to migrate the new version of connector to the production app, i am wondering how i could use on your new version with the control utility to iterate and fix issues on the production app? i feel your version is much simplified and better. we may not need to have a perfect version....

**Comment by asturur** [comment]
I think somehow i lost the magnetic effect of the controls while approaching a connecting point on an object, but we should check this pr together, that bug can be fixed

**Comment by usamshen** [comment]
I merged the latest changes to the master branch for testing. I realized there might be questions about our collaboration on the code, especially since the function spans both the Fabric.js component and the new BoardX_web front end.

Given the significant refactoring we're undergoing on both BoardX_web and CanvasX, I didn't follow the PR process. For now, let's prioritize resolving the connector issues. Once those are addressed, we can establish a baseline and start adhering to a formal change process. Additionally, we need to decide how to switch to importing the Fabric.js library instead of forking it.

I'm currently testing based on the BoardX_web project, not the code sandbox under canvasx. I believe we should simplify the sandbox demo. are you using the sandbox demo for testing or you are using something else?

Here are a few questions I've encountered:

- Control1 and Control2 were removed from the XConnector field list . This change prevents the connectors from loading. Should we add these back, or is there a new design ?
- The snapping feature works the first time a connector is drawn but disappears when the arrow is selected and moved.
- The control point does not adapt when moving the fromPoint or toPoint to dock to the sticky note's docking point.
the control point calculating code is here now at: https://github.com/boardx/boardx-web/blob/develop/src/boardApp/boardMenu/modeHandlers/useLineActions.ts,

**Comment by usamshen** [comment]
I pushed a commit to fix a few issues:
1. pathControls: i added //@ts-nocheck as there is type error caused build failed
2. change toId, fromId, to toObjectId, fromObjectId, apply to all files
3. XConnector: 
add type for canvas, for solving type error, add fields 
 declare fromPoint: XY;
  declare toPoint: XY;
  declare control1: XY;
  declare control2: XY;
revise extendedProperties for toObject to get right fields to saveData
in update function, update, frompoint, topoint, control1, control2

the 1, 2 issues of the four issues above were solved now.

**Comment by asturur** [comment]
Yes i expected we could check the pr together and talk before merging.
For testing i used the demo code, the connector page you get when you do npm start. Is there anything else that can be used with more features?

**Comment by usamshen** [comment]
> Yes i expected we could check the pr together and talk before merging. For testing i used the demo code, the connector page you get when you do npm start. Is there anything else that can be used with more features?

If you agree, we could define three projects:

boardx_web: This is a Next.js project that serves as the open-source BoardX app with full features. It integrates AI to enhance both individual and collaborative work, includes logic for undo/redo, sync, and data mutation, and connects to the boardx-backend, which is a NestJS project.

boardx_demo: This is the current CodeSandbox setup used for demonstrating the canvasx feature. It can be published to a demo website to showcase additional components based on Fabric.js for digital whiteboard applications. However, it will be simplified and will not include the full features of BoardX to avoid added complexity. Some features, especially those dependent on the Redux store, are better suited for the boardx_web project.

boardx_canvasx: This project imports Fabric.js as a library and extends the canvas and widgets for whiteboard applications. Features that are not ideal to add directly to Fabric.js can be implemented here.

I struggled a bit with this definition, as I initially thought of building the CodeSandbox into a full-featured open-source project. However, I haven't figured out how to cleanly separate the code between the demo and the web project.

**Pull request merged**
